apiVersion: apps/v1
kind: Deployment
metadata:
  name: heroiccharacter-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heroiccharacter-frontend
  template:
    metadata:
      labels:
        app: heroiccharacter-frontend
    spec:
      containers:
        - name: frontend
          image: heroiccharacter_frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: heroiccharacter-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: heroiccharacter-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
